spring:
  profiles:
    active: dev
  application:
    name: alanmall-order

mybatis:
  mapper-locations: classpath*:com/itcrazy/alanmall/order/dal/mapper/*Mapper.xml"
  type-aliases-package: com.itcrazy.alanmall.order.dal.entity


sendTag: false

#支付配置
payconfig:
  weixin:
    #应用ID
    appId: wx9f1fa58451efa9b2
    #商户ID号
    mchID: 1576040561
    #秘钥
    key: QS8rrOISuu8LojP1OFd8xmswB7TQCfI1
    #默认回调地址
    notifyUrl: http://2cw4969042.wicp.vip:50381/wx/result

    #证书存储路径
    certPath: D:/gupaoedu-vip-mall/mall-service/mall-payservice/src/main/resources/apiclient_cert.p12
    #支付安全校验(验签)