spring:
  datasource:
    url: jdbc:mysql://aliyun.alan.com:3307/gpmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redisson:
    address:
      aliyun.alan.com:6379
    timeout: 3000
    data-base: 0

dubbo:
  application:
    name: pay-service
    owner: mathyoung
  protocol:
    name: dubbo
    port: 20995
  registry:
    address: zookeeper://aliyun.alan.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://aliyun.alan.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    basePackages: com.itcrazy.alanmall.pay.service
