spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/itcrazy/alanmall/user/sql/sqlmap_*.xml"
  type-aliases-package: com.itcrazy.alanmall.user.model

#server:
#  port: 8090
