spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/itcrazy/alanmall/user/dal/mapper/*Mapper.xml"
  type-aliases-package: com.itcrazy.alanmall.user.entity

#server:
#  port: 8090
