server:
  port: 8089

mybatis:
  mapper-locations: classpath*:com/itcrazy/alan/leadtest/rabbit/product/rabbitproduct/dal/mapper/*Mapper.xml
  type-aliases-package: com.itcrazy.alan.leadtest.rabbit.product.rabbitproduct.dal.entity

spring:
  rabbitmq:
    username: admin
    password: admin
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    port: 5672
    virtual-host: /
    host: aliyun.alan.com
  datasource:
    url: jdbc:mysql://aliyun.alan.com:3307/gpmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
