dubbo:
  application:
    name: tomcat-service
    owner: mathyoung
  protocol:
    name: dubbo
    port: 20991
  registry:
#    address: zookeeper://139.196.44.115:2181
    address: zookeeper://aliyun.alan.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
#    address: zookeeper://139.196.44.115:2181
    address: zookeeper://aliyun.alan.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    basePackages: com.itcrazy.alanmall.tomcat.service
  provider:
    cluster: failover
    retries: 3

spring:
  datasource:
#    url: jdbc:mysql://139.196.44.115:3307/gpmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/gpmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000


#  redis:
#    host: 192.168.89.139
#    port: 6379
#  cache:
#    type: redis
  #    cache-names: tomcatTest


  redis:
    #      192.168.1.101:7291,
    #      192.168.1.101:7292,
    #      192.168.1.105:7293,
    #      192.168.1.105:7294,
    #      192.168.1.106:7295,
    #      192.168.1.106:7296
    host: aliyun.alan.com
    timeout: 10000
