dubbo:
  application:
    name: alanmall-user
    owner: mathyoung
  registry:
    address: zookeeper://nexus.maven.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://nexus.maven.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    basePackages: com.itcrazy.alanmall.user

#spring:
#  redisson:
#    address:
#      nexus.maven.com:6379
#    timeout: 3000
#    data-base: 0
user:
 captchaFlag : true

