spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redisson:
    #    address: redis.gpmall.com:6379
    address: nexus.maven.com:6379
    #    address: redis4gpmall.redis.rds.aliyuncs.com:6379
    #    password: redis4GPMALL
    timeout: 3000
    database: 0

dubbo:
  application:
    name: merchant-service
    owner: Yang
  protocol:
    name: dubbo
    port: 20992
  registry:
    address: zookeeper://nexus.maven.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://nexus.maven.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.itcrazy.alanmall.mscard.service
