dubbo:
  application:
    name: order-provider
    owner: mathyoung
  registry:
    address: zookeeper://aliyun.alan.com:2181
    check: true
    simplified: true
    group: dubbo-dev
  metadata-report:
    address: zookeeper://aliyun.alan.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    basePackages: com.itcrazy.alanmall.order.service

spring:
  redisson:
    address: aliyun.alan.com:6379
  rabbitmq:
    username: admin
    password: admin
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    port: 5672
    virtual-host: /
    host: aliyun.alan.com




