spring:
  profiles:
    active: dev
  rabbitmq:
    username: admin
    password: admin
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    port: 5672
    virtual-host: /
    host: aliyun.alan.com

server:
  port: 8090