dubbo:
  application:
    name: alanmall-tomcat
    owner: mathyoung
  registry:
#    address: zookeeper://172.16.111.59:2181
    address: zookeeper://aliyun.alan.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
#    address: zookeeper://172.16.111.59:2181
    address: zookeeper://aliyun.alan.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    basePackages: com.itcrazy.alanmall.tomcat



